= Docker image for Neo4j

This image is a build of Neo4j's Docker image.

_*Note:* As of Neo4j version 4.4+, Neo4j's official image supports both amd64 (Intel chip) and arm64 (Apple silicon chip) architectures (see `OS/ARCH` for each tag). If you are using Neo4j prior to v4.4, then you will need to use the https://hub.docker.com/r/neo4j/neo4j-arm64-experimental/tags[neo4j/neo4j-arm64-experimental^] DockerHub repository and alter the Dockerfile and runNeo4j.sh script to pull that image._

== Building and running the image

You can build the image on your local machine with the following command:

[source,shell]
----
cd docker/

docker build . -t <project>
----

_*Note:* <project> in the above command is the repository you are referencing. If using my build of Neo4j's image, you can put `jmreif/neo4j`. If you want to build straight from Neo4j's image, you can put `neo4j:4.4.1`. Both should yield the same results, as my build doesn't make changes to Neo4j's image._

To run the container, execute the following command in the root directory:

[source,shell]
----
./runNeo4j.sh
----

You can run a `docker ps` at the command line to verify the container is still running.