#pull base image
#----------------
FROM neo4j:5.22.0

#author
#-------
LABEL org.opencontainers.image.authors="Jennifer Reif,jennifer.reif@neo4j.com,jmhreif.com"

#build the container
#--------------------
EXPOSE 7474 7473 7687
