#pull base image
#----------------
FROM neo4j:4.4.1

#author
#-------
LABEL org.opencontainers.image.authors="Jennifer Reif,jennifer@thehecklers.org,@JMHReif"

#build the container
#--------------------
EXPOSE 7474 7473 7687
