#pull base image
#----------------
FROM neo4j/neo4j-arm64-experimental:4.3.3-arm64

#author
#-------
LABEL org.opencontainers.image.authors="Jennifer Reif,jennifer@thehecklers.org,@JMHReif"

#build the container
#--------------------
EXPOSE 7474 7473 7687
